#!usr/bin/env bash
# Display PID and process name for processes containing the word "bash"

for pid in /proc/[0-9]*
do
    process_name=$(cat "$pid/cmdline" 2>/dev/null | tr -d '\0')  # Get process name from /proc/<pid>/cmdline
    if [[ "$process_name" == *bash* ]]; then
        echo "PID: ${pid#/proc/} | Process Name: $process_name"
    fi
done
