#!/usr/bin/env bash
# Displays the time for 12 horus and 59 minutes.
#   Displays hours from 0 to 12
#   Displays minutes from 1 to 59


hours=0

while [ $hours -le 12 ]
do
  minutes=1
  while [ $minutes -le 59 ]
  do
    echo "$hours:$minutes"
    ((minutes++))
  done

  ((hours++))
done
